scrape_configs:
  - job_name: 'MovingHouseAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          application: 'Moving House Application'